# Generated by Django 3.2.13 on 2022-05-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
