# Generated by Django 2.2.13 on 2022-08-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('url', models.URLField(null=True)),
                ('is_hidden', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('url', models.URLField(null=True)),
                ('slot', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('is_default', models.BooleanField()),
                ('base_experience', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('abilities', models.ManyToManyField(related_name='pokemon_abilities', to='pokemon.PokemonAbility')),
                ('types', models.ManyToManyField(related_name='pokemon_types', to='pokemon.PokemonType')),
            ],
        ),
    ]
