# Generated by Django 3.2.13 on 2022-05-25 12:57

from django.db import migrations
import asyncio
from asgiref.sync import sync_to_async

from pokemon.pokemon_api import list_pokemon

def populate_pokemon(apps, schema_editor):
    # This migration assumes there's nothing in the table
    # Probably won't always be true. Add some checking here
    # to determine what to do with existing data
    Pokemon = apps.get_model('pokemon', 'Pokemon')

    async def get_pokemon_list():
        pokemon_list = list_pokemon()
        async for pokemon_page in pokemon_list:
            pokemon_list = [
                Pokemon(**pokemon_data)
                for pokemon_data in pokemon_page
            ]
            await sync_to_async(Pokemon.objects.bulk_create)(pokemon_list)
    asyncio.run(get_pokemon_list())

def empty_pokemon(apps, schema_editor):
    # This rollback will remove ALL data in the table
    # There should definitely be a warning here.
    Pokemon = apps.get_model('pokemon', 'Pokemon')
    Pokemon.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_pokemon, empty_pokemon)
    ]
