# Generated by Django 3.2.13 on 2022-05-25 12:57

from django.db import migrations

from pokemon.pokemon_api import list_pokemon

def populate_pokemon(apps, schema_editor):
    Pokemon = apps.get_model('pokemon', 'Pokemon')

    for pokemon_page in list_pokemon():
        pokemon_list = [
            Pokemon(**pokemon_data)
            for pokemon_data in pokemon_page
        ]
        Pokemon.objects.bulk_create(pokemon_list) 


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_pokemon)
    ]
