# Generated by Django 3.2.15 on 2022-08-30 11:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemonmatuscaught',
            options={'verbose_name_plural': 'Pokemons Matus Caught'},
        ),
        migrations.AddField(
            model_name='pokemonmatuscaught',
            name='abilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pokemonmatuscaught',
            name='pokemon_id',
            field=models.IntegerField(db_index=True, help_text='External Pokemon ID', unique=True),
        ),
    ]
