# Generated by Django 3.2.15 on 2022-08-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20220830_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonmatuscaught',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
